# Generated by Django 5.2.6 on 2025-10-06 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('club_country', models.CharField(max_length=100)),
                ('club_city', models.CharField(max_length=100)),
                ('club_stadium', models.CharField(max_length=100)),
                ('club_capacity', models.IntegerField()),
                ('club_coach', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2)),
                ('player_number', models.IntegerField()),
                ('player_country', models.CharField(max_length=100)),
                ('player_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footapp.clubs')),
            ],
        ),
    ]
