# Generated by Django 5.2.7 on 2025-10-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='club_logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/'),
        ),
        migrations.AddField(
            model_name='players',
            name='player_photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos/'),
        ),
    ]
